// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "pdfPreview.enabled": boolean;
      "pdfStateInit.enabled": boolean;
      "pdfPrefs.scrollMode": number;
      "pdfPrefs.scale": string;
    };
  }
}
